### ISSUE TITLE
Pelaajien tuominen kentälle

### ISSUE THREAD

**Issue by psykkis** [Alt-Org/Altzone#15]
ensin 2 pelaajaa samaan peliin pallottelemaan kentän puolikkaalta toiselle > testaus
pelaajien spawnaaminen kentälle mahdollisimman joustavalla systeemillä (eli ei kovakoodattuna peliä kahdelle pelaajalle)

**Comment by piia-ruuska** [comment]
Päivitys 7060b4eb889cbbd9e7a202a46f8234b341f9fcbf
Luotu spawnauspointteja, joihin player entity teleportataan sen luomisen jälkeen.

PlayerMovementSystemiin tehty muutos mergetty tähän branchiin f17e628ac551e1c95b3222cd59d963458c7e0ee8

Spawnaussysteemi + pelaajan liikkumiset valmiita testattavaksi useammalla pelaajalla.

**Comment by piia-ruuska** [comment]
Useampi commit tehty, 
- b940ef7b7040d1d393354f6a8d3b7496cac82326
- a60fdf83461abb3f983474866e9866dd481eca55
- 48a64139103c779e374ccb17c5addd0809165683
- 135108172aa4694f1378f998d192b384f4ff0fb5
- e1de983495ff958f569486a0dac7e3a971eb8911

Sähläsin githubin branchien kanssa, joten commiteista tuli vähän sekamelska, mutta se kaikki pitäisi olla korjattuna.

Tilanne pelaajan liikkumisen kanssa moninpelissä:
Pelaajat liikkuvat vain omaa ruutua napsautettaessa, mutta lähtevät yhä ruudun alareunaa kohti, eikä klikattuun kohtaan.
