### ISSUE TITLE
GameControllers

### ISSUE THREAD

**Issue by Niklas603619** [Alt-Org/Altzone#60]
GameSessionController: PeliState hallinta
GameViewController: Unity puolen hallinta - aanet, UI, etc

Perus palikat paikalleen

Hahmojen grafiikka hahmovalintaan: Altzone\Assets\MenuUi\Graphics\DefencegalleryGraphics

**Comment by psykkis** [comment]
@Reizka kuinka pitkälle oot tehnyt? @Hanska7 tulee mukaan tekemään...

**Comment by psykkis** [comment]
Olisko paikallaan tehdä samassa branchissa? olkaa yhteyksissä ja sopikaa asian käytännöistä

**Comment by psykkis** [comment]
Mikä näiden tehtävien tila on? @Reizka 

Henrillä on vielä tekemättä HP ja timanttilaskuri

**Comment by Niklas603619** [comment]
Tilanne valmis ja Battle-devissä
