### ISSUE TITLE
Objektin liikkuminen siihen mihin pelaaja klikkaa

### ISSUE THREAD

**Issue by psykkis** [Alt-Org/Altzone#7]

**Comment by piia-ruuska** [comment]
Tämän hetken tilanne:
Pelaajan klikkaus huomioidaan ja sen koordinaatit otetaan talteen (joutunee hienosäätämään, koska testaamiseen käyttämäni kenttä taitaa olla eri päin kuin lopullinen pelikenttä). Debug.log viesti näyttää klikkauksen koordinaatit testatessa. Pelaaja liikkuu, mutta ei klikkauskohtaan, kuten kuuluisi.
Player prefab laitettu QuantumUser/Resources alle luotuun Prefabs-kansioon.

Kaikki pelaajan liikkumiseen liittyvä commitattu feature/PlayerMovement branchiin.

**Comment by piia-ruuska** [comment]
Tilannepäivitys:
Tutoriaalivideoita katsottu, dokumentaatiota luettu ja esimerkkipeli ladattu tarkastelua varten. Ei koodimuutoksia.

**Comment by piia-ruuska** [comment]
Tilannepäivitys:
Niklas korjasi pelaajan liikkumisen. Nyt pelaaja menee oikeaan suuntaan klikatessa. Täytyy laittaa vielä jatkamaan matkaa kunnes saavuttaa määränpään.

- KCC on nyt poistettu käytöstä, kaikki jäljet siitä pitäisi olla siivottu pois
- PlayerLink uudelleennimetty PlayerData, sisältää nyt myös pelaajan nopeuden ja tulee tulevaisuudessa sisältämään muitakin pelaajan tietoja

**Comment by piia-ruuska** [comment]
Tilannepäivitys: 518312dead5098c1e95349c858cad55ab41aafdd ja 472c1e1428619c50facfa4203c05878fadc832a4
Pelaaja liikkuu nyt määränpäähän asti.
Pientä siivoilua myös.

**Comment by Niklas603619** [comment]
laitoin commenteja 518312dead5098c1e95349c858cad55ab41aafdd committiin

**Comment by piia-ruuska** [comment]
ae7187db7fe46ce585b57115c3a7ad4a6faf7a37
Kommenttien mukainen nimimuutos tehty ja turhat välit poistettu

**Comment by piia-ruuska** [comment]
Korjaus f75d600bb986c441dad99df9d74a784a523be66b
Korjattu niin, ettei pelaaja lähde liikkumaan spawnauksen jälkeen kohti 0,0,0 koordinaatteja. Ongelma tuli ilmi spawnaussysteemin kanssa.
